language: node_js

node_js:
  - "0.12"
  - "0.10"
  - "iojs-v1.1.0"

install:
  - npm install -g esprima-fb@15001.1.0-dev-harmony-fb
  - npm install -g jscs
  - npm install -g mocha
  - npm install -g bower
  - npm install -g gulp
  - npm install
  - bower install

before_script:
  - gulp init

script:
  - npm test